# Netlify configuration for HTSUS Tariff searcher

[build]
  base    = "TariffHTSUSearcher"   # path within the repo
  command = "echo 'No build command required'"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["node_modules/node-fetch/**"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
