# This is a configuration file for Netlify.
# It tells Netlify how to build and deploy your site, including where to find serverless functions.
# Create this file in the root directory of your project.

[build]
  # This command is not strictly necessary for a simple HTML site, but it's good practice.
  # If you had a build step, you would put the command here (e.g., "npm run build").
  base = "tariffhtsusearcher"
  command = "echo 'No build command required'"
  
  # This tells Netlify that your published site is in the root directory.
  publish = "."

[functions]
  # This explicitly tells Netlify where to find your serverless functions.
  directory = "netlify/functions/"
  
  # This specifies the Node.js runtime version. 
  # Using a recent LTS (Long-Term Support) version is recommended.
  node_bundler = "esbuild"
  included_files = ["node_modules/node-fetch/**"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200


