# Netlify configuration for HTSUS Tariff searcher

[build]
  base    = "TariffHTSUSearcher"   # path within the repo
  command = "echo 'No build command required'"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[scheduled.functions]]
  name = "refresh-hts"
  cron = "0 3 * * *"

[[scheduled.functions]]
  name = "refresh-fr232"
  cron = "30 3 * * *"

[[scheduled.functions]]
  name = "refresh-regs232"
  cron = "0 4 * * *"

[[scheduled.functions]]
  name = "build-search-index"
  cron = "0 5 * * *"
